# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/natalia/disertation/datarecordings

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/natalia/disertation/datarecordings

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/natalia/disertation/datarecordings/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/natalia/disertation/datarecordings/CMakeFiles /home/natalia/disertation/datarecordings/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/natalia/disertation/datarecordings/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named butterworth

# Build rule for target.
butterworth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 butterworth
.PHONY : butterworth

# fast build rule for target.
butterworth/fast:
	$(MAKE) -f CMakeFiles/butterworth.dir/build.make CMakeFiles/butterworth.dir/build
.PHONY : butterworth/fast

#=============================================================================
# Target rules for targets named lmsfilter

# Build rule for target.
lmsfilter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lmsfilter
.PHONY : lmsfilter

# fast build rule for target.
lmsfilter/fast:
	$(MAKE) -f CMakeFiles/lmsfilter.dir/build.make CMakeFiles/lmsfilter.dir/build
.PHONY : lmsfilter/fast

#=============================================================================
# Target rules for targets named clBP

# Build rule for target.
clBP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clBP
.PHONY : clBP

# fast build rule for target.
clBP/fast:
	$(MAKE) -f clBP/CMakeFiles/clBP.dir/build.make clBP/CMakeFiles/clBP.dir/build
.PHONY : clBP/fast

butterworth.o: butterworth.cpp.o

.PHONY : butterworth.o

# target to build an object file
butterworth.cpp.o:
	$(MAKE) -f CMakeFiles/butterworth.dir/build.make CMakeFiles/butterworth.dir/butterworth.cpp.o
.PHONY : butterworth.cpp.o

butterworth.i: butterworth.cpp.i

.PHONY : butterworth.i

# target to preprocess a source file
butterworth.cpp.i:
	$(MAKE) -f CMakeFiles/butterworth.dir/build.make CMakeFiles/butterworth.dir/butterworth.cpp.i
.PHONY : butterworth.cpp.i

butterworth.s: butterworth.cpp.s

.PHONY : butterworth.s

# target to generate assembly for a file
butterworth.cpp.s:
	$(MAKE) -f CMakeFiles/butterworth.dir/build.make CMakeFiles/butterworth.dir/butterworth.cpp.s
.PHONY : butterworth.cpp.s

lmsfilter.o: lmsfilter.cpp.o

.PHONY : lmsfilter.o

# target to build an object file
lmsfilter.cpp.o:
	$(MAKE) -f CMakeFiles/lmsfilter.dir/build.make CMakeFiles/lmsfilter.dir/lmsfilter.cpp.o
.PHONY : lmsfilter.cpp.o

lmsfilter.i: lmsfilter.cpp.i

.PHONY : lmsfilter.i

# target to preprocess a source file
lmsfilter.cpp.i:
	$(MAKE) -f CMakeFiles/lmsfilter.dir/build.make CMakeFiles/lmsfilter.dir/lmsfilter.cpp.i
.PHONY : lmsfilter.cpp.i

lmsfilter.s: lmsfilter.cpp.s

.PHONY : lmsfilter.s

# target to generate assembly for a file
lmsfilter.cpp.s:
	$(MAKE) -f CMakeFiles/lmsfilter.dir/build.make CMakeFiles/lmsfilter.dir/lmsfilter.cpp.s
.PHONY : lmsfilter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... butterworth"
	@echo "... lmsfilter"
	@echo "... clBP"
	@echo "... butterworth.o"
	@echo "... butterworth.i"
	@echo "... butterworth.s"
	@echo "... lmsfilter.o"
	@echo "... lmsfilter.i"
	@echo "... lmsfilter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

